(function(){
"use strict";
var DATA=window.__TOTEM_GRAPH_DATA__;
if(!DATA){document.body.innerHTML='<main style="padding:24px;color:white;background:#050b14">graph data missing: viewer/generated/graph-data.js</main>';return}
var NS="http://www.w3.org/2000/svg",mode="2d",selected=null,svg=document.getElementById("graph2d"),pane2d=document.getElementById("pane2d"),pane3d=document.getElementById("pane3d"),canvas=document.getElementById("graph3d"),info=document.getElementById("info");
var modules=DATA.modules||[],externals=DATA.externalNodes||[],features=DATA.features||[],contracts=DATA.contracts||[],code=DATA.code||{indexed:false,nodes:[],edges:[]},moduleMap=new Map(modules.map(function(x){return[x.id,x]})),all=modules.concat(externals);
document.getElementById("snapshot").textContent=((DATA.snapshot&&DATA.snapshot.date)||"unknown")+" snapshot";
document.getElementById("stats").textContent=modules.length+" modules｜"+features.length+" features｜"+contracts.length+" contracts｜"+((code.nodes||[]).length)+" code nodes";
function E(name,attrs){var n=document.createElementNS(NS,name);Object.keys(attrs||{}).forEach(function(k){n.setAttribute(k,String(attrs[k]))});return n}
function short(v,n){v=String(v||"");return v.length>n?v.slice(0,n-1)+"…":v}
function item(text){var d=document.createElement("div");d.className="item";d.textContent=text;return d}
function showInfo(title,body,sections){document.getElementById("infoTitle").textContent=title;document.getElementById("infoBody").textContent=body||"";var box=document.getElementById("infoContent");box.replaceChildren();(sections||[]).forEach(function(section){var h=document.createElement("h3");h.textContent=section.title;box.appendChild(h);(section.items||[]).forEach(function(v){box.appendChild(item(v))})});info.hidden=false}
function nodeGroup(obj,p,kind,onClick){var g=E("g",{"class":"node "+kind,transform:"translate("+p.x+" "+p.y+")",tabindex:"0",role:"button"}),w=p.w||240,h=p.h||68;g.appendChild(E("rect",{width:w,height:h,rx:12}));var t=E("text",{x:14,y:Math.min(27,h/2+2),"class":"label"});t.textContent=short(obj.name||obj.label||obj.title||obj.id,34);g.appendChild(t);if(h>=50){var s=E("text",{x:14,y:Math.min(49,h-10),"class":"sub"});s.textContent=short(obj.version||obj.path||obj.role||obj.type||"",46);g.appendChild(s)}var click=onClick||function(){};g.addEventListener("click",click);g.addEventListener("keydown",function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();click()}});return g}
function edgeColor(type){return type==="hard-core"?"#60a5fa":type==="fabric-suggests"?"#fbbf24":type==="external-service"?"#22d3ee":"#a78bfa"}
function rankOf(n){return Number(n.rankHint||4)}
function layoutOverview(){var ranks=new Map(),pos=new Map(),xs={1:80,2:520,3:980,4:1370},gap=106,top=120,maxRows=1;all.forEach(function(n){var r=rankOf(n);if(!ranks.has(r))ranks.set(r,[]);ranks.get(r).push(n)});ranks.forEach(function(list){maxRows=Math.max(maxRows,list.length)});var height=Math.max(900,top*2+(maxRows-1)*gap+80);ranks.forEach(function(list,rank){list.sort(function(a,b){return(a.name||a.id).localeCompare(b.name||b.id)});var start=top+(maxRows-list.length)*gap/2;list.forEach(function(n,i){pos.set(n.id,{x:xs[rank]||80,y:start+i*gap,w:310,h:72})})});return{pos:pos,width:1740,height:height}}
function overviewPath(a,b,type,lane,height){var ax=a.x+a.w,ay=a.y+a.h/2,bx=b.x,by=b.y+b.h/2;if(bx>ax+36){var mid=ax+(bx-ax)*.5;return"M"+ax+" "+ay+" C"+mid+" "+ay+" "+mid+" "+by+" "+bx+" "+by}var bottom=type==="observer-provider"||(type==="runtime-optional"&&lane%2===1),rail=bottom?height-42-lane*15:42+lane*15;return"M"+ax+" "+ay+" C"+(ax+58)+" "+ay+" "+(ax+58)+" "+rail+" "+(ax+8)+" "+rail+" L"+(bx-8)+" "+rail+" C"+(bx-58)+" "+rail+" "+(bx-58)+" "+by+" "+bx+" "+by}
function contractEndpoints(c){return c.from&&c.to?[c.from,c.to]:null}
function isCoreModule(m){return rankOf(m)===3}
function renderOverview(){selected=null;svg.replaceChildren();info.hidden=true;var L=layoutOverview();svg.setAttribute("viewBox","0 0 "+L.width+" "+L.height);svg.setAttribute("width",L.width);svg.setAttribute("height",L.height);var defs=E("defs"),types=["hard-core","fabric-suggests","runtime-optional","observer-provider","eventbus","external-service"];types.forEach(function(k){var m=E("marker",{id:"arr-"+k,markerWidth:8,markerHeight:8,refX:7,refY:4,orient:"auto"}),p=E("path",{d:"M0 0L8 4 0 8Z",fill:edgeColor(k)});m.appendChild(p);defs.appendChild(m)});svg.appendChild(defs);var eg=E("g"),lane=0;contracts.forEach(function(c){var ep=contractEndpoints(c);if(!ep)return;var a=L.pos.get(ep[0]),b=L.pos.get(ep[1]);if(!a||!b)return;var reverse=b.x<=a.x+a.w+36;eg.appendChild(E("path",{d:overviewPath(a,b,c.type,reverse?lane++:0,L.height),"class":"edge "+c.type+(reverse?" reverse":""),"marker-end":"url(#arr-"+c.type+")"}))});svg.appendChild(eg);var ng=E("g"),title=E("text",{x:80,y:68,"class":"section-title"});title.textContent="MODULE FLOW →";ng.appendChild(title);all.forEach(function(m){var p=L.pos.get(m.id);if(!p)return;var kind=moduleMap.has(m.id)?("module "+(isCoreModule(m)?"core":"")):"external";ng.appendChild(nodeGroup(m,p,kind,function(){moduleMap.has(m.id)?renderModule(m.id):showInfo(m.name||m.id,"External node",[])}))});svg.appendChild(ng);draw3d()}
function detailLine(a,b){var ax=a.x+a.w,ay=a.y+a.h/2,bx=b.x,by=b.y+b.h/2,mid=ax+(bx-ax)*.52;return"M"+ax+" "+ay+" C"+mid+" "+ay+" "+mid+" "+by+" "+bx+" "+by}
function renderModule(id){selected=id;svg.replaceChildren();var mod=moduleMap.get(id);if(!mod)return;var feats=features.filter(function(f){return f.ownerId===id}),nodes=code.nodes||[],cats=nodes.filter(function(n){return n.moduleId===id&&n.type==="code-category"}),files=nodes.filter(function(n){return n.moduleId===id&&(n.type==="code-file"||n.type==="test-file")}),symbols=nodes.filter(function(n){return n.moduleId===id&&n.type==="code-symbol"}),featureStart=120,featureGap=76,featureEnd=featureStart+Math.max(1,feats.length)*featureGap,codeStart=featureEnd+130,plans=[],cursor=codeStart+80;
cats.forEach(function(c){var cf=files.filter(function(f){return f.category===c.category}),filePlans=[],fc=cursor;cf.forEach(function(f){var sf=symbols.filter(function(s){return s.path===f.path}),block=Math.max(66,sf.length*38+8);filePlans.push({file:f,symbols:sf,y:fc,block:block});fc+=block+10});var h=Math.max(72,fc-cursor);plans.push({category:c,files:filePlans,start:cursor,height:h});cursor+=h+34});
var H=Math.max(920,cursor+120),modulePos={x:45,y:55,w:290,h:82},featureRoot={x:390,y:55,w:280,h:64},codeRoot={x:390,y:codeStart,w:280,h:64};svg.setAttribute("viewBox","0 0 1780 "+H);svg.setAttribute("width",1780);svg.setAttribute("height",H);var eg=E("g"),ng=E("g");ng.appendChild(nodeGroup(mod,modulePos,"module "+(isCoreModule(mod)?"core":""),function(){showInfo(mod.name,mod.role,[{title:"Feature groups",items:mod.featureGroups||[]}])}));ng.appendChild(nodeGroup({name:"Curated features",version:feats.length+" branches"},featureRoot,"feature",function(){showInfo("Curated architecture","Validated feature layer",[])}));eg.appendChild(E("path",{d:detailLine(modulePos,featureRoot),"class":"edge detail"}));feats.forEach(function(f,i){var p={x:390,y:featureStart+i*featureGap,w:360,h:62};ng.appendChild(nodeGroup({name:f.title,version:"curated feature"},p,"feature",function(){showInfo(mod.name+"｜"+f.title,f.summary,[])}));eg.appendChild(E("path",{d:"M"+(featureRoot.x+140)+" "+(featureRoot.y+featureRoot.h)+" L"+(featureRoot.x+140)+" "+(p.y+p.h/2)+" L"+p.x+" "+(p.y+p.h/2),"class":"edge detail"}))});
ng.appendChild(nodeGroup({name:"Generated code detail",version:code.indexed?"index metadata":"index unavailable"},codeRoot,"category",function(){showInfo("Generated code detail","Only factual file / symbol metadata. It cannot redefine curated contracts.",[])}));eg.appendChild(E("path",{d:"M"+(modulePos.x+modulePos.w/2)+" "+(modulePos.y+modulePos.h)+" L"+(modulePos.x+modulePos.w/2)+" "+(codeRoot.y+32)+" L"+codeRoot.x+" "+(codeRoot.y+32),"class":"edge detail"}));
if(!cats.length){var empty=E("text",{x:760,y:codeStart+38,"class":"empty-code"});empty.textContent="No local code index detail yet; build-index / impact will update graph-data.js.";ng.appendChild(empty)}
plans.forEach(function(plan){var c=plan.category,cp={x:760,y:plan.start+plan.height/2-30,w:245,h:60};ng.appendChild(nodeGroup({name:c.label,version:c.count+" files"},cp,"category"));eg.appendChild(E("path",{d:detailLine(codeRoot,cp),"class":"edge detail"}));plan.files.forEach(function(fp){var f=fp.file,filePos={x:1045,y:fp.y,w:315,h:56};ng.appendChild(nodeGroup({name:f.label,version:f.path},filePos,f.type==="test-file"?"test":"file",function(){showInfo(f.label,f.path,[{title:"Generated metadata",items:["category: "+f.category,"indexed symbols: "+f.symbolCount]}])}));eg.appendChild(E("path",{d:detailLine(cp,filePos),"class":"edge detail"}));fp.symbols.forEach(function(s,k){var sp={x:1410,y:fp.y+k*38,w:285,h:32};ng.appendChild(nodeGroup({name:s.label,version:"symbol"},sp,"symbol",function(){showInfo(s.label,s.path,[])}));eg.appendChild(E("path",{d:detailLine(filePos,sp),"class":"edge detail"}))})})});svg.appendChild(eg);svg.appendChild(ng);var rel=contracts.filter(function(c){return c.from===id||c.to===id||(c.relatedNodes||[]).includes(id)});showInfo(mod.name+" "+(mod.version||""),mod.role,[{title:"Summary",items:["Curated features: "+feats.length,"Generated categories: "+cats.length,"Visualized files: "+files.length,"Related contracts: "+rel.length]},{title:"Related contracts",items:rel.map(function(c){return c.type+"｜"+c.from+" → "+c.to+"｜"+(c.feature||c.id)})}]);draw3d()}
function showContracts(){showInfo(contracts.length+" validated contracts","Curated relationship list",[{title:"Contracts",items:contracts.map(function(c,i){return String(i+1).padStart(2,"0")+"｜"+c.type+"｜"+c.from+" → "+c.to+"｜"+(c.feature||c.id)})}])}
document.getElementById("overview").addEventListener("click",renderOverview);document.getElementById("contracts").addEventListener("click",showContracts);document.getElementById("mode2d").addEventListener("click",function(){mode="2d";pane2d.hidden=false;pane3d.hidden=true;this.setAttribute("aria-pressed","true");document.getElementById("mode3d").setAttribute("aria-pressed","false")});document.getElementById("mode3d").addEventListener("click",function(){mode="3d";pane2d.hidden=true;pane3d.hidden=false;this.setAttribute("aria-pressed","true");document.getElementById("mode2d").setAttribute("aria-pressed","false");resize3d();draw3d()});
var cam={yaw:-.48,pitch:.22,zoom:1.02},drag=null;
function resize3d(){var d=window.devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d))}
function project(p,w,h){var cy=Math.cos(cam.yaw),sy=Math.sin(cam.yaw),cp=Math.cos(cam.pitch),sp=Math.sin(cam.pitch),x=p.x*cy-p.z*sy,z=p.x*sy+p.z*cy,y=p.y*cp-z*sp;z=p.y*sp+z*cp;var scale=cam.zoom*820/Math.max(200,920+z);return{x:w/2+x*scale,y:h/2+y*scale,scale:scale,z:z}}
function scene3d(){var nodes=[],edges=[],collection=all;collection.forEach(function(m){var rank=rankOf(m),same=collection.filter(function(x){return rankOf(x)===rank}),idx=same.indexOf(m);nodes.push({id:m.id,label:m.name||m.id,type:moduleMap.has(m.id)?"module":"external",rank:rank,x:(rank-2.5)*300,y:(idx-(same.length-1)/2)*125,z:0})});contracts.forEach(function(c){if(c.from&&c.to)edges.push({from:c.from,to:c.to,type:c.type})});if(selected){(code.nodes||[]).filter(function(n){return n.moduleId===selected&&n.type==="code-category"}).forEach(function(c,i,arr){nodes.push({id:c.id,label:c.label,type:"category",x:560,y:(i-(arr.length-1)/2)*95,z:190});edges.push({from:selected,to:c.id,type:"detail"})})}return{nodes:nodes,edges:edges}}
function draw3d(){if(mode!=="3d")return;var r=canvas.getBoundingClientRect(),d=window.devicePixelRatio||1,ctx=canvas.getContext("2d"),w=r.width,h=r.height;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle="#050b14";ctx.fillRect(0,0,w,h);var S=scene3d(),pp=new Map();S.nodes.forEach(function(n){pp.set(n.id,project(n,w,h))});S.edges.forEach(function(e){var a=pp.get(e.from),b=pp.get(e.to);if(!a||!b)return;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=e.type==="hard-core"?"#60a5fa":e.type==="fabric-suggests"?"#fbbf24":e.type==="external-service"?"#22d3ee":e.type==="detail"?"#34d399":"#a78bfa";ctx.globalAlpha=.48;ctx.lineWidth=1.8;ctx.stroke()});ctx.globalAlpha=1;S.nodes.slice().sort(function(a,b){return pp.get(a.id).z-pp.get(b.id).z}).forEach(function(n){var p=pp.get(n.id),radius=Math.max(5,10*p.scale);ctx.beginPath();ctx.arc(p.x,p.y,radius,0,Math.PI*2);ctx.fillStyle=n.type==="external"?"#fbbf24":n.type==="category"?"#34d399":n.rank===3?"#22d3ee":"#60a5fa";ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=9;ctx.fill();ctx.shadowBlur=0;ctx.font="12px system-ui";ctx.fillStyle="#dbeafe";ctx.fillText(short(n.label,24),p.x+radius+6,p.y+4)})}
canvas.addEventListener("pointerdown",function(e){drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.classList.add("dragging")});canvas.addEventListener("pointermove",function(e){if(!drag||drag.id!==e.pointerId)return;cam.yaw+=(e.clientX-drag.x)*.008;cam.pitch=Math.max(-1.2,Math.min(1.2,cam.pitch+(e.clientY-drag.y)*.006));drag.x=e.clientX;drag.y=e.clientY;draw3d()});function endDrag(e){if(!drag||drag.id!==e.pointerId)return;drag=null;canvas.classList.remove("dragging")}canvas.addEventListener("pointerup",endDrag);canvas.addEventListener("pointercancel",endDrag);canvas.addEventListener("wheel",function(e){e.preventDefault();cam.zoom=Math.max(.45,Math.min(2.5,cam.zoom*Math.exp(-e.deltaY*.001)));draw3d()},{passive:false});window.addEventListener("resize",function(){if(mode==="3d"){resize3d();draw3d()}});
renderOverview();
}());
